// 原 router/module/monitor.js 改 .ts，路径与映射不变。
// 后续视图拆分如需分片加载请在此处调整。

const monitor: Record<string, () => Promise<unknown>> = {
  MonitorDashboard: () => import('views/dashboard/index.vue'), // 概览
  MonitorComputeServer: () => import('views/compute/server/index.vue'),
  MonitorComputeCloud: () => import('views/compute/cloud/platform.vue'), // 云平台
  MonitorVm: () => import('views/compute/vm.vue'), // 云主机
  MonitorCloudVcenter: () => import('views/compute/cloud/vcenter/index.vue'),
  MonitorCloudCNware: () => import('views/compute/cloud/cnware/index.vue'),
  MonitorCloudHuaweiFC: () => import('views/compute/cloud/fc/index.vue'), // fusionsphere
  MonitorCloudInspurRail: () => import('views/compute/cloud/inspurRail/index.vue'),
  MonitorCloudInspurCloud: () => import('views/compute/cloud/InspurCloud/index.vue'),
  MonitorCloudUsphere: () => import('views/compute/cloud/usphere/index.vue'), // 紫光云
  MonitorCloudSangforHCI: () => import('views/compute/cloud/sangforHCI/index.vue'),
  MonitorCloudSangforSCP: () => import('views/compute/cloud/sangforSCP/index.vue'),
  MonitorCloudOpenStack: () => import('views/compute/cloud/openstack/index.vue'),
  MonitorCloudEasyStack: () => import('views/compute/cloud/easystack/index.vue'),
  MonitorCloudFusion: () => import('views/compute/cloud/FusionCloud/index.vue'),
  MonitorCloudManageOne: () => import('views/compute/cloud/FusionCloud/index.vue'),
  MonitorCloudHmc: () => import('views/compute/cloud/hmc/index.vue'),
  MonitorCloudK8s: () => import('views/compute/container/kubernetes/index.vue'),
  MonitorCloudTianyi: () => import('views/compute/cloud/tianyi/index.vue'),
  MonitorCloudAliyun: () => import('views/compute/cloud/aliyun/index.vue'),
  MonitorCloudLenovo: () => import('views/compute/cloud/lenovo/index.vue'),
  MonitorApsarastack: () => import('views/compute/cloud/apsarastack/index.vue'),
  MonitorCloudQcloud: () => import('views/compute/cloud/qcloud/index.vue'),
  MonitorYYJCloudQcloud: () => import('views/compute/cloud/yyjqcloud/index.vue'),
  MonitorCloudAzure: () => import('views/compute/cloud/azure/index.vue'),
  MonitorCloudCecStack: () => import('views/compute/cloud/cecStack/index.vue'),
  MonitorCloudHuawei: () => import('views/compute/cloud/huawei/index.vue'),
  MonitorCloudH3C: () => import('views/compute/cloud/h3c/index.vue'),
  MonitorCloudZstack: () => import('views/compute/cloud/zstack/index.vue'),
  MonitorCloudSmart: () => import('views/compute/cloud/smart/index.vue'),
  MonitorCloudCloudTower: () => import('views/compute/cloud/cloudTower/index.vue'),
  MonitorContainerDetail: () => import('views/compute/cloud/vcenter/platformMonitorDetail.vue'),
  MonitorDetailList: () => import('views/compute/cloud/vcenter/platformMonitorDetail.vue'),
  MonitorFocusList: () => import('views/storage/huawei/list.vue'),
  MonitorHuawei: () => import('views/storage/huawei/index.vue'),
  MonitorHuaweiDetail: () => import('views/storage/huawei/monitorDetail.vue'),
  MonitorDell: () => import('views/storage/huawei/index.vue'),
  MonitorDellDetail: () => import('views/storage/huawei/monitorDetail.vue'),
  MonitorSDNList: () => import('views/network/sdn/index.vue'),
  thresholdValue: () => import('views/alarm_manage/monitorPolicy/index.vue'),
  CreateMonitorPolicy: () => import('views/alarm_manage/monitorPolicy/add.vue'),
  ModifyMonitorPolicy: () => import('views/alarm_manage/monitorPolicy/add.vue'),
  MonitorTemplate: () => import('views/alarm_manage/template/index.vue'),
  CreateMonitorTemplate: () => import('views/alarm_manage/template/add.vue'),
  ModifyMonitorTemplate: () => import('views/alarm_manage/template/add.vue'),
  CurrentMonitor: () => import('views/alarm_manage/current/index.vue'),
  HistoryMonitor: () => import('views/alarm_manage/history/index.vue'),
  DistributePolicy: () => import('views/alarm_manage/policy/shieldManage.vue'),
  OpenStackServerMonitor: () => import('views/compute/cloud/platformMonitor/openstack.vue'),
  OpenStackVmMonitor: () => import('views/compute/cloud/platformMonitor/openstack_vm.vue'),
  EasyStackServerMonitor: () => import('views/compute/cloud/platformMonitor/easystack.vue'),
  EasyStackVmMonitor: () => import('views/compute/cloud/platformMonitor/easystack_vm.vue'),
  vCenterServerMonitor: () => import('views/compute/cloud/platformMonitor/vcenterHost.vue'),
  vCenterVmMonitor: () => import('views/compute/cloud/platformMonitor/vcenterVm.vue'),
  mOneServerMonitor: () => import('views/compute/cloud/platformMonitor/manageone_host.vue'),
  mOneVmMonitor: () => import('views/compute/cloud/platformMonitor/manageone_vm.vue'),
  SmartxServerMonitor: () => import('views/compute/cloud/platformMonitor/smartx_host.vue'),
  SmartxVmMonitor: () => import('views/compute/cloud/platformMonitor/smartx_vm.vue'),
  CloudTowerServerMonitor: () => import('views/compute/cloud/platformMonitor/cloudTower_host.vue'),
  CloudTowerVmMonitor: () => import('views/compute/cloud/platformMonitor/cloudTower_vm.vue'),
  monitorDatabaseDetail: () => import('views/compute/cloud/vcenter/platformMonitorDetail.vue'),
  huaweiStorageList: () => import('views/storage/huawei/list.vue'),
  yyjQcloudVmMonitor: () => import('views/compute/cloud/platformMonitor/yyjQcloudVm.vue'),
  yyjQcloudHostMonitor: () => import('views/compute/cloud/platformMonitor/yyjQcloudHost.vue'),

  // 数据库监控
  DatabaseMysql: () => import('views/databases/mysql.vue'),
  DatabaseMssql: () => import('views/databases/sqlserver.vue'),
  DatabasePostGreSQL: () => import('views/databases/postgresql.vue'),
  DatabaseOracle: () => import('views/databases/oracle.vue'),
  DatabaseRedis: () => import('views/databases/redis.vue'),
  DatabaseMemCached: () => import('views/databases/memcached.vue'),
  DatabaseMongodb: () => import('views/databases/mongodb.vue'),
  RdbmsMysqlDetail: () => import('views/databases/mysqlDetail.vue'),
  RdbmsMssqlDetail: () => import('views/databases/sqlserverDetail.vue'),
  RdbmsPostgresqlDetail: () => import('views/databases/postgresqlDetail.vue'),
  RdbmsOracleDetail: () => import('views/databases/oracleDetail.vue'),
  NosqlRedisDetail: () => import('views/databases/redisDetail.vue'),
  NosqlMemcachedDetail: () => import('views/databases/memcachedDetail.vue'),
  NosqlMongodbDetail: () => import('views/databases/mongodbDetail.vue'),
  MonitorKafka: () => import('views/middleware/kafka.vue'),
  MonitorRabbitMQ: () => import('views/middleware/rabbitmq.vue'),
  MonitorZookeeper: () => import('views/middleware/zookeeper.vue'),
  MonitorEtcd: () => import('views/middleware/etcd.vue'),

  // 分布式存储
  MonitorStorageDistribute: () => import('views/storage/distribute/platform.vue'),
  MonitorStorageXsky: () => import('views/storage/distribute/xsky/index.vue'),

  // 交换机
  MonitorSmisFabric: () => import('views/storage/switch/list.vue'),
  MonitorCisco: () => import('views/storage/switch/cisco.vue'),
  MonitorCiscoDetail: () => import('views/compute/cloud/vcenter/platformMonitorDetail.vue')
}

export default monitor
