// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-ui/lib/alert')['default']
    ElBadge: typeof import('element-ui/lib/badge')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElCascader: typeof import('element-ui/lib/cascader')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElProgress: typeof import('element-ui/lib/progress')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioButton: typeof import('element-ui/lib/radio-button')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElStep: typeof import('element-ui/lib/step')['default']
    ElSteps: typeof import('element-ui/lib/steps')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTabPane: typeof import('element-ui/lib/tab-pane')['default']
    ElTabs: typeof import('element-ui/lib/tabs')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElTransfer: typeof import('element-ui/lib/transfer')['default']
    ElUpload: typeof import('element-ui/lib/upload')['default']
  }
}

export { }
