const ops = {
  ThresholdValue: () => import('views/monitor/alarm_manage/monitorPolicy/index.vue'),
  CreateMonitorPolicy: () => import('views/monitor/alarm_manage/monitorPolicy/add.vue'), // 新增告警策略
  ModifyMonitorPolicy: () => import('views/monitor/alarm_manage/monitorPolicy/add.vue'), // 编辑告警策略
  MonitorTemplate: () => import('views/monitor/alarm_manage/template/index.vue'), // 告警模板
  CurrentMonitor: () => import('views/monitor/alarm_manage/current/index.vue'),
  HistoryMonitor: () => import('views/monitor/alarm_manage/history/index.vue'),
  HostECS: () => import('views/monitor/alarm_manage/policy/resourceManage.vue'),
  DistributePolicy: () => import('views/monitor/alarm_manage/policy/shieldManage.vue'),
  VcMonitor: () => import('views/monitor/virtual/vcenter/vm.vue'),
  OpMonitor: () => import('views/monitor/virtual/openstack/index.vue'),
  MoMonitor: () => import('views/monitor/virtual/manageone/index.vue'),
  DatabaseMysql: () => import('views/monitor/database/mysql.vue'),
  DatabaseMssql: () => import('views/monitor/database/sqlserver.vue'),
  DatabaseRedis: () => import('views/monitor/database/redis.vue'),
  DatabaseMongodb: () => import('views/monitor/database/mongodb.vue'),
  DatabasePostgreSQL: () => import('views/monitor/database/postgresql.vue'),
  DatabaseMemcached: () => import('views/monitor/database/memcached.vue'),
  RdbmsMysqlDetail: () => import('views/monitor/database/mysqlDetail.vue'),
  RdbmsMssqlDetail: () => import('views/monitor/database/sqlserverDetail.vue'),
  RdbmsPostgresqlDetail: () => import('views/monitor/database/postgresqlDetail.vue'),
  NosqlRedisDetail: () => import('views/monitor/database/redisDetail.vue'),
  NosqlMemcachedDetail: () => import('views/monitor/database/memcachedDetail.vue'),
  NosqlMongodbDetail: () => import('views/monitor/database/mongodbDetail.vue'),
  MonitorDatabaseDetail: () => import('views/monitor/virtual/vcenter/platformMonitorDetail.vue'),
  MonitorMiddlewareDetail: () => import('views/monitor/virtual/vcenter/platformMonitorDetail.vue'),
  MonitorKafka: () => import('views/monitor/middleware/kafka.vue'),
  MonitorRabbitMQ: () => import('views/monitor/middleware/rabbitmq.vue'),
  MonitorZookeeper: () => import('views/monitor/middleware/zookeeper.vue'),
  MonitorEtcd: () => import('views/monitor/middleware/etcd.vue'),
  MonitorDetailList: () => import('views/monitor/virtual/vcenter/platformMonitorDetail.vue') // 告警详情
}
export default ops
