const picBaseUrl = '/web-common-resource/img/platform/'
export const logoObj = {
  OPENSTACK: `${picBaseUrl}op.png`,
  EASYSTACK: `${picBaseUrl}easystack.png`,
  VMWARE: `${picBaseUrl}vcenter.png`,
  FUSIONSPHERE: `${picBaseUrl}fusionComputer.png`,
  SMARTX: `${picBaseUrl}smart.png`,
  H3C: `${picBaseUrl}huasanyun.png`,
  JDCLOUD: `${picBaseUrl}jingdongyun.png`,
  ALIYUN: `${picBaseUrl}aliyun.png`,
  ACAS: `${picBaseUrl}aliyun.png`,
  TIANYI: `${picBaseUrl}ty.png`,
  FUSIONCLOUD: `${picBaseUrl}huawei.png`,
  MANAGEONE: `${picBaseUrl}huawei.png`,
  TENCENT: `${picBaseUrl}tencent.png`,
  TCE: `${picBaseUrl}tencent.png`,
  KINGCLOUD: `${picBaseUrl}kingcloud.png`,
  KUBERNETES: `${picBaseUrl}k8s.png`,
  POWERVC: `${picBaseUrl}powervc.png`,
  HMC: `${picBaseUrl}ibm-hmc.png`,
  HUAWEI: `${picBaseUrl}huawei.png`,
  HCSO: `${picBaseUrl}huawei.png`,
  AZURE: `${picBaseUrl}azure.png`,
  IBMSTORE: `${picBaseUrl}ibm.png`,
  OCEANSTORE: `${picBaseUrl}huaweicunchu.png`,
  CLARIIONSTORE: `${picBaseUrl}EMC.png`,
  DELLSTORE: `${picBaseUrl}dell.png`,
  xksy: `${picBaseUrl}xsky.png`,
  ceph: `${picBaseUrl}ceph.png`,
  APIC: `${picBaseUrl}apic.png`,
  NSX: `${picBaseUrl}nsx.png`,
  AGILE: `${picBaseUrl}agile.png`,
  // CAMPUS: `${picBaseUrl}campus.png`,
  F5: `${picBaseUrl}bigip.png`,
  brocadeswitch: `${picBaseUrl}boke.png`,
  ciscoswitch: `${picBaseUrl}sike.png`,
  AWS: `${picBaseUrl}aws.png`,
  QCLOUD: `${picBaseUrl}qcloud.png`,
  HORIZON: `${picBaseUrl}vczm.png`,
  JUMPSERVER: `${picBaseUrl}jumpserver.png`,
  TENABLE: `${picBaseUrl}tenable.png`,
  HILLSTONE: `${picBaseUrl}firewall.png`,
  VEEAM: `${picBaseUrl}veeam.png`,
  CAMPUS: `${picBaseUrl}h3c.png`,
  VOLCENGINE: `${picBaseUrl}volcengine.png`
}
